plugins:
    - jekyll-sitemap
defaults:
  -
    scope:
      path: "*.html"
    values:
      sitemap: false
  -
    scope:
      path: informatique/**
      path: flashcards/**
    values:
      sitemap: false
