plugins:
    - jekyll-sitemap
exclude:
    - documentation_res/
    - edit_svg/
    - informatique/
    - output/
    - "*.tex"
    - "*.sty"
    - "*.tfm"
    - "*.pfb"
    - "*.md"
    - L3_Anglais/input/
    - L3_Anglais/localcards
defaults:
    -
          scope:
            path: "*.html"
          values:
            sitemap: false
    -
        scope:
            path: informatique/**
        values:
            sitemap: false
    -
        scope:
            path: Documentation.pdf
        values:
            sitemap: false
    -
        scope:
            path: exercices/**
        values:
            sitemap: false
    -
        scope:
            path: flashcards/**
        values:
            sitemap: false
    -
        scope:
            path: MP2I/**
        values:
            sitemap: false
    -
        scope:
            path: MPI/**
        values:
            sitemap: false
    -
        scope:
            path: L3_anglais/**
        values:
            sitemap: false
    -
        scope:
            path: L3S1/**
        values:
            sitemap: false

