plugins:
    - jekyll-sitemap
exclude:
    - informatique/
    - documentation_res/
defaults:
    -
          scope:
            path: "*.html"
          values:
            sitemap: false
    -
        scope:
            path: informatique/**
        values:
            sitemap: false
    -
        scope:
            path: Documentation.pdf
        values:
            sitemap: false
    -
        scope:
            path: exercices/**
        values:
            sitemap: false
    -
        scope:
            path: flashcards/**
        values:
            sitemap: false
    -
        scope:
            path: MP2I/**
        values:
            sitemap: false
    -
        scope:
            path: MPI/**
        values:
            sitemap: false
    -
        scope:
            path: L3/anglais/**
        values:
            sitemap: false

